[package]
name = "movey_app"
version = "0.1.0"
authors = ["East Agile"]
edition = "2018"

[[bin]]
name = "cli"
path = "src/main.rs"

[dependencies]
clap = "2"
term = "0.5"

[build-dependencies]
clap = "2"

